security:
    # https://symfony.com/doc/current/security.html#registering-the-user-hashing-passwords
    password_hashers:
        Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface: 'auto'

    # https://symfony.com/doc/current/security.html#loading-the-user-the-user-provider
    providers:
        direction_users:
            memory:
                users:
                    adjoint:
                        password: '%env(APP_ADJOINT_PASSWORD_HASH)%'
                        roles: ['ROLE_DIRECTION']
                    directrice:
                        password: '%env(APP_DIRECTRICE_PASSWORD_HASH)%'
                        roles: ['ROLE_DIRECTION']
        animator_users:
            entity:
                class: App\Entity\Animator
                property: username
        all_users:
            chain:
                providers: ['direction_users', 'animator_users']

    firewalls:
        dev:
            # Ensure dev tools and static assets are always allowed
            pattern: ^/(_profiler|_wdt|assets|build|styles)/
            security: false
        api:
            pattern: ^/api
            stateless: true
            provider: animator_users
            entry_point: App\Security\ApiTokenAuthenticator
            custom_authenticators:
                - App\Security\ApiTokenAuthenticator
        main:
            lazy: true
            provider: all_users
            form_login:
                login_path: app_login
                check_path: app_login
                enable_csrf: true
                default_target_path: app_after_login
            logout:
                path: app_logout
                target: app_login

    # Note: Only the *first* matching rule is applied
    access_control:
        - { path: ^/api/login$, roles: PUBLIC_ACCESS }
        - { path: ^/api, roles: ROLE_ANIMATOR }
        - { path: ^/connexion$, roles: PUBLIC_ACCESS }
        - { path: ^/apres-connexion$, roles: IS_AUTHENTICATED_FULLY }
        - { path: ^/mon-mot-de-passe$, roles: ROLE_ANIMATOR }
        - { path: ^/, roles: ROLE_DIRECTION }

when@test:
    security:
        password_hashers:
            # Password hashers are resource-intensive by design to ensure security.
            # In tests, it's safe to reduce their cost to improve performance.
            Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface:
                algorithm: auto
                cost: 4 # Lowest possible value for bcrypt
                time_cost: 3 # Lowest possible value for argon
                memory_cost: 10 # Lowest possible value for argon
