<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

final class Version20260526203000 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Add daily animator task assignments';
    }

    public function up(Schema $schema): void
    {
        $this->addSql('CREATE TABLE daily_task_assignment (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, task_date DATE NOT NULL, task_type VARCHAR(50) NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, season_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_8CFE3DFB4EC001D1 ON daily_task_assignment (season_id)');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_DAILY_TASK_SEASON_DAY_TASK ON daily_task_assignment (season_id, task_date, task_type)');
        $this->addSql('CREATE TABLE daily_task_assignment_animator (daily_task_assignment_id INT NOT NULL, animator_id INT NOT NULL, PRIMARY KEY (daily_task_assignment_id, animator_id))');
        $this->addSql('CREATE INDEX IDX_192759A4EF3DCE28 ON daily_task_assignment_animator (daily_task_assignment_id)');
        $this->addSql('CREATE INDEX IDX_192759A470FBD26D ON daily_task_assignment_animator (animator_id)');
        $this->addSql('ALTER TABLE daily_task_assignment ADD CONSTRAINT FK_8CFE3DFB4EC001D1 FOREIGN KEY (season_id) REFERENCES season (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE daily_task_assignment_animator ADD CONSTRAINT FK_192759A4EF3DCE28 FOREIGN KEY (daily_task_assignment_id) REFERENCES daily_task_assignment (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE daily_task_assignment_animator ADD CONSTRAINT FK_192759A470FBD26D FOREIGN KEY (animator_id) REFERENCES animator (id) ON DELETE CASCADE');
    }

    public function down(Schema $schema): void
    {
        $this->addSql('ALTER TABLE daily_task_assignment_animator DROP CONSTRAINT FK_192759A4EF3DCE28');
        $this->addSql('ALTER TABLE daily_task_assignment_animator DROP CONSTRAINT FK_192759A470FBD26D');
        $this->addSql('ALTER TABLE daily_task_assignment DROP CONSTRAINT FK_8CFE3DFB4EC001D1');
        $this->addSql('DROP TABLE daily_task_assignment_animator');
        $this->addSql('DROP TABLE daily_task_assignment');
    }
}
