<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

final class Version20260529210000 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Introduce central users and internal messaging tables';
    }

    public function up(Schema $schema): void
    {
        $this->addSql("CREATE TABLE app_user (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, username VARCHAR(80) NOT NULL, password_hash VARCHAR(255) NOT NULL, role VARCHAR(20) NOT NULL, first_name VARCHAR(80) NOT NULL, last_name VARCHAR(80) NOT NULL, active BOOLEAN NOT NULL, must_change_password BOOLEAN NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY(id))");
        $this->addSql('CREATE UNIQUE INDEX UNIQ_APP_USER_USERNAME ON app_user (username)');
        $this->addSql("INSERT INTO app_user (username, password_hash, role, first_name, last_name, active, must_change_password, created_at, updated_at) SELECT username, password_hash, 'animator', first_name, last_name, active, must_change_password, created_at, created_at FROM animator ON CONFLICT (username) DO NOTHING");

        $this->addSql('ALTER TABLE animator ADD user_id INT DEFAULT NULL');
        $this->addSql("UPDATE animator SET user_id = app_user.id FROM app_user WHERE app_user.username = animator.username AND app_user.role = 'animator'");
        $this->addSql('CREATE UNIQUE INDEX UNIQ_ANIMATOR_USER ON animator (user_id)');
        $this->addSql('ALTER TABLE animator ADD CONSTRAINT FK_ANIMATOR_USER FOREIGN KEY (user_id) REFERENCES app_user (id) ON DELETE SET NULL NOT DEFERRABLE');

        $this->addSql('ALTER TABLE api_token ADD user_id INT DEFAULT NULL');
        $this->addSql('UPDATE api_token SET user_id = animator.user_id FROM animator WHERE api_token.animator_id = animator.id');
        $this->addSql('ALTER TABLE api_token ALTER animator_id DROP NOT NULL');
        $this->addSql('ALTER TABLE api_token ALTER user_id SET NOT NULL');
        $this->addSql('CREATE INDEX IDX_API_TOKEN_USER ON api_token (user_id)');
        $this->addSql('ALTER TABLE api_token ADD CONSTRAINT FK_API_TOKEN_USER FOREIGN KEY (user_id) REFERENCES app_user (id) ON DELETE CASCADE NOT DEFERRABLE');

        $this->addSql('ALTER TABLE mobile_device_token ADD user_id INT DEFAULT NULL');
        $this->addSql('UPDATE mobile_device_token SET user_id = animator.user_id FROM animator WHERE mobile_device_token.animator_id = animator.id');
        $this->addSql('ALTER TABLE mobile_device_token ALTER animator_id DROP NOT NULL');
        $this->addSql('ALTER TABLE mobile_device_token ALTER user_id SET NOT NULL');
        $this->addSql('CREATE INDEX IDX_MOBILE_DEVICE_TOKEN_USER ON mobile_device_token (user_id)');
        $this->addSql('ALTER TABLE mobile_device_token ADD CONSTRAINT FK_MOBILE_DEVICE_TOKEN_USER FOREIGN KEY (user_id) REFERENCES app_user (id) ON DELETE CASCADE NOT DEFERRABLE');

        $this->addSql("CREATE TABLE message (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, sender_id INT NOT NULL, audience VARCHAR(30) NOT NULL, subject VARCHAR(160) DEFAULT NULL, body TEXT NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY(id))");
        $this->addSql('CREATE INDEX IDX_MESSAGE_SENDER ON message (sender_id)');
        $this->addSql('ALTER TABLE message ADD CONSTRAINT FK_MESSAGE_SENDER FOREIGN KEY (sender_id) REFERENCES app_user (id) ON DELETE CASCADE NOT DEFERRABLE');

        $this->addSql("CREATE TABLE message_recipient (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, message_id INT NOT NULL, recipient_id INT NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, read_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, PRIMARY KEY(id))");
        $this->addSql('CREATE INDEX IDX_MESSAGE_RECIPIENT_MESSAGE ON message_recipient (message_id)');
        $this->addSql('CREATE INDEX IDX_MESSAGE_RECIPIENT_RECIPIENT ON message_recipient (recipient_id)');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_MESSAGE_RECIPIENT ON message_recipient (message_id, recipient_id)');
        $this->addSql('ALTER TABLE message_recipient ADD CONSTRAINT FK_MESSAGE_RECIPIENT_MESSAGE FOREIGN KEY (message_id) REFERENCES message (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE message_recipient ADD CONSTRAINT FK_MESSAGE_RECIPIENT_RECIPIENT FOREIGN KEY (recipient_id) REFERENCES app_user (id) ON DELETE CASCADE NOT DEFERRABLE');
    }

    public function down(Schema $schema): void
    {
        $this->addSql('ALTER TABLE message_recipient DROP CONSTRAINT FK_MESSAGE_RECIPIENT_MESSAGE');
        $this->addSql('ALTER TABLE message_recipient DROP CONSTRAINT FK_MESSAGE_RECIPIENT_RECIPIENT');
        $this->addSql('ALTER TABLE message DROP CONSTRAINT FK_MESSAGE_SENDER');
        $this->addSql('DROP TABLE message_recipient');
        $this->addSql('DROP TABLE message');

        $this->addSql('ALTER TABLE mobile_device_token DROP CONSTRAINT FK_MOBILE_DEVICE_TOKEN_USER');
        $this->addSql('DROP INDEX IDX_MOBILE_DEVICE_TOKEN_USER');
        $this->addSql('ALTER TABLE mobile_device_token DROP user_id');
        $this->addSql('ALTER TABLE mobile_device_token ALTER animator_id SET NOT NULL');

        $this->addSql('ALTER TABLE api_token DROP CONSTRAINT FK_API_TOKEN_USER');
        $this->addSql('DROP INDEX IDX_API_TOKEN_USER');
        $this->addSql('ALTER TABLE api_token DROP user_id');
        $this->addSql('ALTER TABLE api_token ALTER animator_id SET NOT NULL');

        $this->addSql('ALTER TABLE animator DROP CONSTRAINT FK_ANIMATOR_USER');
        $this->addSql('DROP INDEX UNIQ_ANIMATOR_USER');
        $this->addSql('ALTER TABLE animator DROP user_id');
        $this->addSql('DROP TABLE app_user');
    }
}
