<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

final class Version20260526223000 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Add mobile API tokens and outing creator tracking';
    }

    public function up(Schema $schema): void
    {
        $this->addSql('CREATE TABLE api_token (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, token_hash VARCHAR(64) NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, last_used_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, expires_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, animator_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_7BA2F5EBB3BC57DA ON api_token (token_hash)');
        $this->addSql('CREATE INDEX IDX_7BA2F5EB70FBD26D ON api_token (animator_id)');
        $this->addSql('ALTER TABLE api_token ADD CONSTRAINT FK_7BA2F5EB70FBD26D FOREIGN KEY (animator_id) REFERENCES animator (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE outing ADD created_by_id INT DEFAULT NULL');
        $this->addSql('ALTER TABLE outing ADD CONSTRAINT FK_F2A10625B03A8386 FOREIGN KEY (created_by_id) REFERENCES animator (id) ON DELETE SET NULL NOT DEFERRABLE');
        $this->addSql('CREATE INDEX IDX_F2A10625B03A8386 ON outing (created_by_id)');
    }

    public function down(Schema $schema): void
    {
        $this->addSql('ALTER TABLE api_token DROP CONSTRAINT FK_7BA2F5EB70FBD26D');
        $this->addSql('ALTER TABLE outing DROP CONSTRAINT FK_F2A10625B03A8386');
        $this->addSql('DROP TABLE api_token');
        $this->addSql('DROP INDEX IDX_F2A10625B03A8386');
        $this->addSql('ALTER TABLE outing DROP created_by_id');
    }
}
