<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

final class Version20260530100000 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Add outing location tracking';
    }

    public function up(Schema $schema): void
    {
        $this->addSql('ALTER TABLE outing ADD route_duration_minutes INT DEFAULT NULL');
        $this->addSql('ALTER TABLE outing ADD location_tracking_enabled BOOLEAN DEFAULT false NOT NULL');

        $this->addSql('CREATE TABLE outing_location_ping (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, outing_id INT NOT NULL, animator_id INT NOT NULL, latitude DOUBLE PRECISION NOT NULL, longitude DOUBLE PRECISION NOT NULL, accuracy DOUBLE PRECISION DEFAULT NULL, heading DOUBLE PRECISION DEFAULT NULL, speed DOUBLE PRECISION DEFAULT NULL, recorded_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_OUTING_LOCATION_OUTING ON outing_location_ping (outing_id)');
        $this->addSql('CREATE INDEX IDX_OUTING_LOCATION_ANIMATOR ON outing_location_ping (animator_id)');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_OUTING_LOCATION_OUTING_ANIMATOR ON outing_location_ping (outing_id, animator_id)');
        $this->addSql('ALTER TABLE outing_location_ping ADD CONSTRAINT FK_OUTING_LOCATION_OUTING FOREIGN KEY (outing_id) REFERENCES outing (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE outing_location_ping ADD CONSTRAINT FK_OUTING_LOCATION_ANIMATOR FOREIGN KEY (animator_id) REFERENCES animator (id) ON DELETE CASCADE NOT DEFERRABLE');
    }

    public function down(Schema $schema): void
    {
        $this->addSql('ALTER TABLE outing_location_ping DROP CONSTRAINT FK_OUTING_LOCATION_OUTING');
        $this->addSql('ALTER TABLE outing_location_ping DROP CONSTRAINT FK_OUTING_LOCATION_ANIMATOR');
        $this->addSql('DROP TABLE outing_location_ping');
        $this->addSql('ALTER TABLE outing DROP route_duration_minutes');
        $this->addSql('ALTER TABLE outing DROP location_tracking_enabled');
    }
}
