<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

final class Version20260527001000 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Add mobile device tokens for push notifications';
    }

    public function up(Schema $schema): void
    {
        $this->addSql('CREATE TABLE mobile_device_token (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, animator_id INT NOT NULL, token VARCHAR(512) NOT NULL, platform VARCHAR(20) NOT NULL, device_name VARCHAR(180) DEFAULT NULL, enabled BOOLEAN NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, last_seen_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_17D083F05F37A13B ON mobile_device_token (token)');
        $this->addSql('CREATE INDEX IDX_17D083F070FBD26D ON mobile_device_token (animator_id)');
        $this->addSql('ALTER TABLE mobile_device_token ADD CONSTRAINT FK_17D083F070FBD26D FOREIGN KEY (animator_id) REFERENCES animator (id) ON DELETE CASCADE NOT DEFERRABLE');
    }

    public function down(Schema $schema): void
    {
        $this->addSql('ALTER TABLE mobile_device_token DROP CONSTRAINT FK_17D083F070FBD26D');
        $this->addSql('DROP TABLE mobile_device_token');
    }
}
