<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

final class Version20260526210500 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Add weekly work shifts for animators';
    }

    public function up(Schema $schema): void
    {
        $this->addSql('CREATE TABLE animator_work_shift (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, work_date DATE NOT NULL, start_time TIME(0) WITHOUT TIME ZONE NOT NULL, lunch_start_time TIME(0) WITHOUT TIME ZONE NOT NULL, lunch_end_time TIME(0) WITHOUT TIME ZONE NOT NULL, end_time TIME(0) WITHOUT TIME ZONE NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, season_id INT NOT NULL, animator_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_D610A6744EC001D1 ON animator_work_shift (season_id)');
        $this->addSql('CREATE INDEX IDX_D610A67470FBD26D ON animator_work_shift (animator_id)');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_WORK_SHIFT_SEASON_ANIMATOR_DAY ON animator_work_shift (season_id, animator_id, work_date)');
        $this->addSql('ALTER TABLE animator_work_shift ADD CONSTRAINT FK_D610A6744EC001D1 FOREIGN KEY (season_id) REFERENCES season (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE animator_work_shift ADD CONSTRAINT FK_D610A67470FBD26D FOREIGN KEY (animator_id) REFERENCES animator (id) ON DELETE CASCADE NOT DEFERRABLE');
    }

    public function down(Schema $schema): void
    {
        $this->addSql('ALTER TABLE animator_work_shift DROP CONSTRAINT FK_D610A6744EC001D1');
        $this->addSql('ALTER TABLE animator_work_shift DROP CONSTRAINT FK_D610A67470FBD26D');
        $this->addSql('DROP TABLE animator_work_shift');
    }
}
