<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

final class Version20260605120000 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Remove mobile API tokens, Firebase device tokens and outing location tracking tables';
    }

    public function up(Schema $schema): void
    {
        $this->addSql('DROP TABLE IF EXISTS outing_location_ping CASCADE');
        $this->addSql('DROP TABLE IF EXISTS mobile_device_token CASCADE');
        $this->addSql('DROP TABLE IF EXISTS api_token CASCADE');
        $this->addSql('ALTER TABLE outing DROP COLUMN IF EXISTS location_tracking_enabled');
    }

    public function down(Schema $schema): void
    {
        $this->addSql('ALTER TABLE outing ADD location_tracking_enabled BOOLEAN DEFAULT false NOT NULL');

        $this->addSql('CREATE TABLE api_token (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, user_id INT NOT NULL, animator_id INT DEFAULT NULL, token_hash VARCHAR(64) NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, last_used_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, expires_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_7BA2F5EBB3BC57DA ON api_token (token_hash)');
        $this->addSql('CREATE INDEX IDX_7BA2F5EBA76ED395 ON api_token (user_id)');
        $this->addSql('CREATE INDEX IDX_7BA2F5EB70FBD26D ON api_token (animator_id)');
        $this->addSql('ALTER TABLE api_token ADD CONSTRAINT FK_7BA2F5EBA76ED395 FOREIGN KEY (user_id) REFERENCES app_user (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE api_token ADD CONSTRAINT FK_7BA2F5EB70FBD26D FOREIGN KEY (animator_id) REFERENCES animator (id) ON DELETE CASCADE NOT DEFERRABLE');

        $this->addSql('CREATE TABLE mobile_device_token (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, user_id INT NOT NULL, animator_id INT DEFAULT NULL, token VARCHAR(512) NOT NULL, platform VARCHAR(20) NOT NULL, device_name VARCHAR(180) DEFAULT NULL, enabled BOOLEAN NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, last_seen_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_17D083F05F37A13B ON mobile_device_token (token)');
        $this->addSql('CREATE INDEX IDX_17D083F0A76ED395 ON mobile_device_token (user_id)');
        $this->addSql('CREATE INDEX IDX_17D083F070FBD26D ON mobile_device_token (animator_id)');
        $this->addSql('ALTER TABLE mobile_device_token ADD CONSTRAINT FK_17D083F0A76ED395 FOREIGN KEY (user_id) REFERENCES app_user (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE mobile_device_token ADD CONSTRAINT FK_17D083F070FBD26D FOREIGN KEY (animator_id) REFERENCES animator (id) ON DELETE CASCADE NOT DEFERRABLE');

        $this->addSql('CREATE TABLE outing_location_ping (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, outing_id INT NOT NULL, animator_id INT NOT NULL, latitude DOUBLE PRECISION NOT NULL, longitude DOUBLE PRECISION NOT NULL, accuracy DOUBLE PRECISION DEFAULT NULL, heading DOUBLE PRECISION DEFAULT NULL, speed DOUBLE PRECISION DEFAULT NULL, recorded_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_OUTING_LOCATION_OUTING ON outing_location_ping (outing_id)');
        $this->addSql('CREATE INDEX IDX_OUTING_LOCATION_ANIMATOR ON outing_location_ping (animator_id)');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_OUTING_LOCATION_OUTING_ANIMATOR ON outing_location_ping (outing_id, animator_id)');
        $this->addSql('ALTER TABLE outing_location_ping ADD CONSTRAINT FK_OUTING_LOCATION_OUTING FOREIGN KEY (outing_id) REFERENCES outing (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE outing_location_ping ADD CONSTRAINT FK_OUTING_LOCATION_ANIMATOR FOREIGN KEY (animator_id) REFERENCES animator (id) ON DELETE CASCADE NOT DEFERRABLE');
    }
}
