<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

final class Version20260526191500 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Create the initial centre aere outing management schema';
    }

    public function up(Schema $schema): void
    {
        $this->addSql('CREATE TABLE season (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name VARCHAR(120) NOT NULL, starts_at DATE NOT NULL, ends_at DATE NOT NULL, active BOOLEAN NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE TABLE child (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, season_id INT NOT NULL, first_name VARCHAR(80) NOT NULL, last_name VARCHAR(80) NOT NULL, age_group VARCHAR(12) NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_22B35429A7C7E4D ON child (season_id)');
        $this->addSql('CREATE TABLE animator (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, first_name VARCHAR(80) NOT NULL, last_name VARCHAR(80) NOT NULL, phone VARCHAR(30) DEFAULT NULL, active BOOLEAN NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE TABLE outing (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, season_id INT NOT NULL, number VARCHAR(30) NOT NULL, destination VARCHAR(180) NOT NULL, departure_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, return_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, transport_mode VARCHAR(80) NOT NULL, picnic_required BOOLEAN NOT NULL, status VARCHAR(20) NOT NULL, validation_comment TEXT DEFAULT NULL, validated_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_8246315F9A7C7E4D ON outing (season_id)');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_8246315F9A7C7E4D34F2C7E ON outing (season_id, number)');
        $this->addSql('CREATE TABLE outing_child (outing_id INT NOT NULL, child_id INT NOT NULL, PRIMARY KEY(outing_id, child_id))');
        $this->addSql('CREATE INDEX IDX_503A302BF58D7487 ON outing_child (outing_id)');
        $this->addSql('CREATE INDEX IDX_503A302BDD62C21B ON outing_child (child_id)');
        $this->addSql('CREATE TABLE outing_animator (outing_id INT NOT NULL, animator_id INT NOT NULL, PRIMARY KEY(outing_id, animator_id))');
        $this->addSql('CREATE INDEX IDX_49F895F4F58D7487 ON outing_animator (outing_id)');
        $this->addSql('CREATE INDEX IDX_49F895F49553C383 ON outing_animator (animator_id)');
        $this->addSql('ALTER TABLE child ADD CONSTRAINT FK_22B35429A7C7E4D FOREIGN KEY (season_id) REFERENCES season (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE outing ADD CONSTRAINT FK_8246315F9A7C7E4D FOREIGN KEY (season_id) REFERENCES season (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE outing_child ADD CONSTRAINT FK_503A302BF58D7487 FOREIGN KEY (outing_id) REFERENCES outing (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE outing_child ADD CONSTRAINT FK_503A302BDD62C21B FOREIGN KEY (child_id) REFERENCES child (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE outing_animator ADD CONSTRAINT FK_49F895F4F58D7487 FOREIGN KEY (outing_id) REFERENCES outing (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE outing_animator ADD CONSTRAINT FK_49F895F49553C383 FOREIGN KEY (animator_id) REFERENCES animator (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
    }

    public function down(Schema $schema): void
    {
        $this->addSql('ALTER TABLE child DROP CONSTRAINT FK_22B35429A7C7E4D');
        $this->addSql('ALTER TABLE outing DROP CONSTRAINT FK_8246315F9A7C7E4D');
        $this->addSql('ALTER TABLE outing_child DROP CONSTRAINT FK_503A302BF58D7487');
        $this->addSql('ALTER TABLE outing_child DROP CONSTRAINT FK_503A302BDD62C21B');
        $this->addSql('ALTER TABLE outing_animator DROP CONSTRAINT FK_49F895F4F58D7487');
        $this->addSql('ALTER TABLE outing_animator DROP CONSTRAINT FK_49F895F49553C383');
        $this->addSql('DROP TABLE outing_child');
        $this->addSql('DROP TABLE outing_animator');
        $this->addSql('DROP TABLE child');
        $this->addSql('DROP TABLE animator');
        $this->addSql('DROP TABLE outing');
        $this->addSql('DROP TABLE season');
    }
}
